### Numpy

NumPy is a fundamental library for scientific computing in Python. It provides support for array and matrices , along with a collection of mathematical function to operate on these data structures. In this lesson , we will cover the basics of NumPy , by focusing on arrays and vectorized operations.

In [3]:
!python.exe -m pip install --upgrade pip

   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.8 MB ? eta -:--:--
   ----- ---------------------------------- 0.3/1.8 MB ? eta -:--:--
   ----------------------- ---------------- 1.0/1.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------- ----------- 1.3/1.8 MB 2.9 MB/s eta 0:00:01
   ---------------------------------- ----- 1.6/1.8 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 1.8/1.8 MB 2.2 MB/s  0:00:01
  Attempting uninstall: pip
    Found existing installation: pip 26.0.1
    Uninstalling pip-26.0.1:
      Successfully uninstalled pip-26.0.1


In [1]:
import numpy as np

### Create array using numpy
### Create a ID array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2=np.array([1,2,3,4,5])
arr2.reshape((1,5)) ## 1 row , 5 columns 

array([[1, 2, 3, 4, 5]])

In [7]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape) ## (2,5) 2 row 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) ## 3 row columns 2d array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
##  Attributes of Numpy Array

arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n" , arr)
print("sHAPE:" , arr.shape) ## (2,3)
print("Number of Dimensions: ",arr.ndim) ## 2
print("Size (Number of Elements): " , arr.size) # 6
print("Data Types:" , arr.dtype) # int64
print("Item Size (in bytes):" , arr.itemsize) # 8 

Array:
 [[1 2 3]
 [4 5 6]]
sHAPE: (2, 3)
Number of Dimensions:  2
Size (Number of Elements):  6
Data Types: int64
Item Size (in bytes): 8


In [17]:
## Numpy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

## Element wise addition
print("Addition: ", arr1+arr2)

## Element wise Substraction
print("Subtraction: " , arr1-arr2)

## Element wise Multiplication
print("Multipication: " , arr1*arr2)

## Element wise Division
print("Division: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multipication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [18]:
## Universal Function
arr=np.array([2,3,4,5,6])
## Square Root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
## Slicing and Indexing Operation

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n" , arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [31]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [37]:
## Modify Array Elements

arr[0,0]=100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [38]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [42]:
### Stastistical Concepts-- Normalization
# To have a mean of 0 and standard deviation of 1
data= np.array([1,2,3,4,5])

## Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## Normalize the data mean=0 std_dev=1
normalized_data= (data - mean) / std_dev
print("Normalized data:" , normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [44]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean: ", mean)

# Median
median = np.median(data)
print("Median: ", median)

# Standard deviation
std_dev = np.std(data)
print("Standard deviation:" , std_dev)

# variance
variance= np.var(data)
print("Variance: ", variance)

Mean:  5.5
Median:  5.5
Standard deviation: 2.8722813232690143
Variance:  8.25


In [50]:
## Logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>5) & (data<=8)]

array([6, 7, 8])